# fly.toml for frontend
app = "accesspaper"  
primary_region = "fra"


[env]
  NODE_ENV = "production"

[http_service]
  internal_port = 80   # Nginx serves on port 80
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
